{% set name = "n2p2" %}
{% set version = "2.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CompPhysVienna/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f1672c09af4ed16a7f396606977e4675a0fee98f04bfd9574907fba4b83a14ef
  patches:
    - app.patch
    - cflags.patch
    - shared.patch

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
  host:
    - python
    - cython
    - {{ mpi }}
    - libblas
    - libcblas
    - gsl
    - eigen
  run:
    - python

test:
  imports:
    - pynnp
  commands:
    - test -f ${PREFIX}/bin/nnp-convert
    - test -f ${PREFIX}/bin/nnp-cutoff
    - test -f ${PREFIX}/bin/nnp-dist
    - test -f ${PREFIX}/bin/nnp-predict
    - test -f ${PREFIX}/bin/nnp-prune
    - test -f ${PREFIX}/bin/nnp-select
    - test -f ${PREFIX}/bin/nnp-symfunc
    - test -f ${PREFIX}/bin/nnp-comp2
    - test -f ${PREFIX}/bin/nnp-dataset
    - test -f ${PREFIX}/bin/nnp-norm
    - test -f ${PREFIX}/bin/nnp-scaling
    - test -f ${PREFIX}/bin/nnp-train

about:
  home: https://compphysvienna.github.io/n2p2/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: n2p2 - A Neural Network Potential Package
  description: |
    This repository (obtain source code here) provides ready-to-use 
    software for high-dimensional neural network potentials in 
    computational physics and chemistry. The methodology behind the 
    Behler-Parinello neural network potentials was first described here:
    J. Behler and M. Parrinello, Phys. Rev. Lett. 98, 146401 (2007)
  doc_url: https://compphysvienna.github.io/n2p2/
  dev_url: https://github.com/CompPhysVienna/n2p2

extra:
  recipe-maintainers:
    - jan-janssen
