{% set name = "n2p2" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CompPhysVienna/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 4acaa255632a7b9811d7530fd52ac7dd0bb3a8e3a3cf8512beadd29b62c1bfef
  patches:
    - app.patch
    - cflags.patch
    - shared.patch

build:
  # prefer mpi as libnnptrain is not supported for nompi
  {% set build = 8 %}
  {% set build = build + 100 %}  # [mpi != 'nompi']
  number: {{ build }}
  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: {{ mpi_prefix }}_py{{ CONDA_PY }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  skip: true  # [not linux]
  run_exports:
     - {{ pin_subpackage("n2p2", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - make
  host:
    - python
    - cython
    - {{ mpi }}  # [mpi != 'nompi']
    - libblas
    - libcblas
    - gsl
    - eigen
    - setuptools
  run:
    - python

test:
  imports:
    - pynnp
  commands:
    - test -f ${PREFIX}/bin/nnp-convert  # [mpi != 'nompi']
    - test -f ${PREFIX}/bin/nnp-cutoff  # [mpi != 'nompi']
    - test -f ${PREFIX}/bin/nnp-dist  # [mpi != 'nompi']
    - test -f ${PREFIX}/bin/nnp-predict  # [mpi != 'nompi']
    - test -f ${PREFIX}/bin/nnp-prune  # [mpi != 'nompi']
    - test -f ${PREFIX}/bin/nnp-select  # [mpi != 'nompi']
    - test -f ${PREFIX}/bin/nnp-symfunc  # [mpi != 'nompi']
    - test -f ${PREFIX}/bin/nnp-comp2  # [mpi != 'nompi']
    - test -f ${PREFIX}/bin/nnp-dataset  # [mpi != 'nompi']
    - test -f ${PREFIX}/bin/nnp-norm  # [mpi != 'nompi']
    - test -f ${PREFIX}/bin/nnp-scaling  # [mpi != 'nompi']
    - test -f ${PREFIX}/bin/nnp-train  # [mpi != 'nompi']

about:
  home: https://compphysvienna.github.io/n2p2/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: n2p2 - A Neural Network Potential Package
  description: |
    This repository (obtain source code here) provides ready-to-use 
    software for high-dimensional neural network potentials in 
    computational physics and chemistry. The methodology behind the 
    Behler-Parinello neural network potentials was first described here:
    J. Behler and M. Parrinello, Phys. Rev. Lett. 98, 146401 (2007)
  doc_url: https://compphysvienna.github.io/n2p2/
  dev_url: https://github.com/CompPhysVienna/n2p2

extra:
  recipe-maintainers:
    - jan-janssen
